# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c040377e6083ecc5bf177bcda33193b0197a5aa629a5befc01083fffd88a3aa3133059a3f29f1b95d8b4cce74ddd32678047dbd7babfed2055943a8fb040f1ee

test:
  secret_key_base: 5cef713590c392f11335c1dd563f818e5ba12b5308866ed96f197cc7116117fccae8a06aaff9a0365852ef6ba0e2d3d5601db66bd29e81e870627474045a7077

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
